// Arduino Template
// Generated by Protogen Configurator — do not edit manually.

#include <LedControl.h>

// ── Hardware ─────────────────────────────────────────────────
#define MATRIX_COUNT      {{MATRIX_COUNT}}
#define MATRIX_DIN_PIN    {{MATRIX_DIN_PIN}}
#define MATRIX_CS_PIN     {{MATRIX_CS_PIN}}
#define MATRIX_CLK_PIN    {{MATRIX_CLK_PIN}}
#define FACE_COUNT        {{FACE_COUNT}}
#define DEFAULT_FACE_ID   {{DEFAULT_FACE_ID}}
#define INPUT_COUNT       {{INPUT_COUNT}}

// Debounce window in milliseconds
#define DEBOUNCE_DELAY_MS 50

// INPUT_PULLDOWN is only natively supported on ESP32/ESP8266.
// On AVR boards this falls back to INPUT; add an external pull-down resistor instead.
#ifndef INPUT_PULLDOWN
#  define INPUT_PULLDOWN INPUT
#endif

// ── Face pixel data (PROGMEM) ─────────────────────────────────
// Each face stores 2 × uint32_t per MAX7219 panel, packed row-by-row:
//   word0 [panelIndex*2 + 0]: rows 0-3, byte per row = (word >> (row*8)) & 0xFF
//   word1 [panelIndex*2 + 1]: rows 4-7, byte per row = (word >> ((row-4)*8)) & 0xFF
// If columns appear mirrored, reverse the byte: reverseByte((word >> (row*8)) & 0xFF)
{{FACE_PROGMEM_DATA}}
// ── Forward declarations ──────────────────────────────────────
void showFace(uint8_t faceId);

// ── Face display state ────────────────────────────────────────
static uint8_t       currentFaceId       = DEFAULT_FACE_ID;
static uint8_t       lastPermanentFaceId = DEFAULT_FACE_ID;
static uint8_t       holdFaceId          = 255; // 255 = none
static uint8_t       timerFaceId         = 255; // 255 = none
static unsigned long timerEnd            = 0;

// ── Action base class ─────────────────────────────────────────
class Action {
public:
  // active=true: input became active; active=false: input released
  virtual void execute(bool active) = 0;
};

// ── Face trigger modes ────────────────────────────────────────
#define FACE_MODE_PERMANENT 0  // switch and stay
#define FACE_MODE_HOLD      1  // show while input is held, then revert
#define FACE_MODE_TIMER     2  // show for a fixed duration, then revert

// ── FaceAction ────────────────────────────────────────────────
class FaceAction : public Action {
public:
  uint8_t  faceId;
  uint8_t  mode;
  uint32_t duration; // ms, relevant for FACE_MODE_TIMER only

  FaceAction(uint8_t faceId, uint8_t mode, uint32_t duration)
    : faceId(faceId), mode(mode), duration(duration) {}

  void execute(bool active) override {
    if (mode == FACE_MODE_PERMANENT) {
      if (active) {
        lastPermanentFaceId = faceId;
        holdFaceId  = 255;
        timerFaceId = 255;
        showFace(faceId);
      }
    } else if (mode == FACE_MODE_HOLD) {
      if (active) {
        holdFaceId = faceId;
        showFace(faceId);
      } else {
        holdFaceId = 255;
        showFace(lastPermanentFaceId);
      }
    } else if (mode == FACE_MODE_TIMER) {
      if (active) {
        timerFaceId = faceId;
        timerEnd    = millis() + duration;
        showFace(faceId);
      }
    }
  }
};

// ── Input (software debouncing) ───────────────────────────────
class Input {
private:
  uint8_t       pin;
  uint8_t       pinModeVal;
  bool          invert;
  Action**      actions;
  uint8_t       actionCount;
  bool          lastRawState;
  bool          stableState;
  unsigned long lastDebounceTime;

public:
  Input(uint8_t pin, uint8_t pinModeVal, bool invert,
        Action** actions, uint8_t actionCount)
    : pin(pin), pinModeVal(pinModeVal), invert(invert),
      actions(actions), actionCount(actionCount),
      lastRawState(false), stableState(false), lastDebounceTime(0) {}

  void begin() {
    pinMode(pin, pinModeVal);
    lastRawState = readRaw();
    stableState  = lastRawState;
  }

  bool readRaw() const {
    bool val = digitalRead(pin) == HIGH;
    return invert ? !val : val;
  }

  void update() {
    bool raw = readRaw();
    if (raw != lastRawState) {
      lastDebounceTime = millis();
      lastRawState     = raw;
    }
    if ((millis() - lastDebounceTime) >= DEBOUNCE_DELAY_MS) {
      if (raw != stableState) {
        stableState = raw;
        if (actions != nullptr) {
          for (uint8_t i = 0; i < actionCount; i++) {
            actions[i]->execute(stableState);
          }
        }
      }
    }
  }
};

// ── Face struct ───────────────────────────────────────────────
struct Face {
  const uint32_t* data;    // PROGMEM: 2 uint32_t per panel
  const char*     name;    // PROGMEM string
  uint8_t         brightness; // 0-15
};

// ── Face name strings (PROGMEM) ───────────────────────────────
{{FACE_NAME_STRINGS}}

// ── Face array ────────────────────────────────────────────────
const Face faces[FACE_COUNT] = {
{{FACE_ARRAY}}
};

// ── Display driver ────────────────────────────────────────────
LedControl lc(MATRIX_DIN_PIN, MATRIX_CLK_PIN, MATRIX_CS_PIN, MATRIX_COUNT);

void showFace(uint8_t faceId) {
  currentFaceId = faceId;
  const Face& f = faces[faceId];
  for (uint8_t p = 0; p < MATRIX_COUNT; p++) {
    lc.setIntensity(p, f.brightness);
    uint32_t w0 = pgm_read_dword(f.data + p * 2);
    uint32_t w1 = pgm_read_dword(f.data + p * 2 + 1);
    for (uint8_t r = 0; r < 4; r++) {
      lc.setRow(p, r,     (uint8_t)((w0 >> (r * 8)) & 0xFF));
      lc.setRow(p, r + 4, (uint8_t)((w1 >> (r * 8)) & 0xFF));
    }
  }
}

// ── Inputs & Actions ──────────────────────────────────────────
#if INPUT_COUNT > 0
{{INPUT_DEFINITIONS}}
Input* inputs[INPUT_COUNT] = {
{{INPUT_ARRAY}}
};
#endif

// ── Setup ─────────────────────────────────────────────────────
void setup() {
  for (uint8_t i = 0; i < MATRIX_COUNT; i++) {
    lc.shutdown(i, false);
    lc.clearDisplay(i);
  }
#if INPUT_COUNT > 0
  for (uint8_t i = 0; i < INPUT_COUNT; i++) {
    inputs[i]->begin();
  }
#endif
  showFace(DEFAULT_FACE_ID);
}

// ── Loop ──────────────────────────────────────────────────────
void loop() {
  // Revert to hold face (if active) or last permanent face when a timer expires
  if (timerFaceId != 255 && millis() >= timerEnd) {
    timerFaceId = 255;
    showFace(holdFaceId != 255 ? holdFaceId : lastPermanentFaceId);
  }
#if INPUT_COUNT > 0
  for (uint8_t i = 0; i < INPUT_COUNT; i++) {
    inputs[i]->update();
  }
#endif
}
